### ISSUE TITLE
Setting new columns after the first time does not work correctly

### ISSUE THREAD

**Issue by henryyi** [simonlevasseur/ko-grid#1]
Steps:
1. Have a grid with a few columns including a select and action column
2. Set new columns via process:
```result.grid().process({
                    columns: cols
                });```
3. Modify the column array (change column and order) and process the new columns again

Expected: New columns are correctly rendered in the order they are sent

Results: Column are not rendered correctly. Headers do not match content. Order does not match columns array.

**Comment by jake-macadamian** [comment]
Upon review we found the cause was the list of current columns were being extracted from the UI layer using a computed observable.  This was updating while the pipeline was still in the middle of processing and so it was populating with invalid data and crashing.

The solution was to use the grid state subscription to fetch the clean copy of the grid state after processing was complete and use the columns data from there.
